
'use client';
import { useEffect,useState } from 'react';
type Config={antiRaidEnabled:boolean;raidJoinLimit:number;raidWindowSeconds:number;logChannelId:string|null};
export default function Settings({guildId}:{guildId:string}){const [config,setConfig]=useState<Config|null>(null);const [message,setMessage]=useState('');const endpoint=`/api/guilds/${guildId}/settings`;
useEffect(()=>{fetch(endpoint).then(r=>{if(!r.ok)throw Error('Unable to load');return r.json()}).then(data=>setConfig({antiRaidEnabled:data.antiRaidEnabled,raidJoinLimit:data.raidJoinLimit,raidWindowSeconds:data.raidWindowSeconds,logChannelId:data.logChannelId??null})).catch(()=>setMessage('Could not load settings'));},[endpoint]);
async function save(){if(!config)return;setMessage('Saving...');try{const r=await fetch(endpoint,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({antiRaidEnabled:config.antiRaidEnabled,raidJoinLimit:config.raidJoinLimit,raidWindowSeconds:config.raidWindowSeconds,logChannelId:config.logChannelId})});if(!r.ok)throw Error('Save failed');setMessage('Settings saved');}catch{setMessage('Unable to save settings');}}
if(!config)return <p>{message||'Loading settings...'}</p>;
return <div className="panel"><h2>Anti-raid monitoring</h2><label className="check"><input type="checkbox" checked={config.antiRaidEnabled} onChange={e=>setConfig({...config,antiRaidEnabled:e.target.checked})}/> Enable join-rate alerts</label><label>Join threshold<input type="number" min="3" max="100" value={config.raidJoinLimit} onChange={e=>setConfig({...config,raidJoinLimit:Number(e.target.value)})}/></label><label>Window (seconds)<input type="number" min="5" max="300" value={config.raidWindowSeconds} onChange={e=>setConfig({...config,raidWindowSeconds:Number(e.target.value)})}/></label><label>Log channel ID<input placeholder="Discord channel ID" value={config.logChannelId||''} onChange={e=>setConfig({...config,logChannelId:e.target.value||null})}/></label><button onClick={save}>Save changes</button><p aria-live="polite">{message}</p><small>Alerts only in this release; no automatic bans or lockdowns.</small></div>}
